version: '3.4'

services:
  pgunit:
    build: 
      context: .
      target: pgunit
    ports:
    - "5432:5432"
    volumes:
    - .:/app/:z

  pgtap:
    build: 
      context: .
      target: pgtap
    ports:
    - "5432:5432"
    volumes:
    - .:/app/:z
