name: jq

on:
    pull_request:
        branches:
            - main
        paths:
            - jq/*

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Install jaq
              run: |
                  cargo install --locked --git https://github.com/01mf02/jaq

            - name: Run tests on jq directory
              working-directory: jq
              run: |
                  ./test-gilded-rose.sh
